### ISSUE TITLE
Quest

### ISSUE THREAD

**Issue by KillaPowa** [holydeew/WoWHellgarve#125]
In Cooking Meat quest on Exile's Reach can't click on the pan when you collect the 5 Meat, and the quest is uncompletable.

**Comment by Lujanamma** [comment]
fixed

**Comment by OMGhixD-OG** [comment]
Re-opening this issue due to a report from an player per Ticket on Discord.

I myself tested this quest on Horde, Monk Undead and it worked fine. However when a Horde, Mage Troll attempted this. It did not work, 

I proceeded to create a Horde, Mage Troll myself and i also was not able to proceed past the "Cooking Meat" quest. I believe this is due to a missing flag value. As i am not able to click the cooking pot at all. (it is not a clickable object for Troll Mages (Probably/Possibly just the troll race in general)

- OMGhixD

**Comment by OMGhixD-OG** [comment]
Issue appears to have been fixed. Closing for now
